project_id = "ecdrxtbclxfpkknasmrw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = false
double_encode_urls = false

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
port = 54329

[functions.ai-insight-guidance]
verify_jwt = false

[functions.buyer-intent-analyzer]
verify_jwt = false

[functions.contextual-help]
verify_jwt = false

[functions.idea-framework-consultant]
verify_jwt = false

[functions.document-processor]
verify_jwt = false