/**
 * Brand Strategy Template
 *
 * Main template orchestrator that assembles all sections into a complete
 * markdown export document.
 */

import type { AggregatedData } from './formatters/DataAggregator';
import type { BrandData } from '@/contexts/BrandContext';
import type { ExportOptions, ExportMetadata } from '../MarkdownExportService';
import { EXPORT_SCHEMA_VERSION } from '../MarkdownExportService';
import * as md from './formatters/MarkdownFormatter';

import { generateExecutiveSummary } from './sections/ExecutiveSummary';
import { generateIDEAFramework } from './sections/IDEAFramework';
import { generateCustomerAvatar } from './sections/CustomerAvatar';
import { generateBrandCanvas } from './sections/BrandCanvas';
import { generateConversationInsights } from './sections/ConversationInsights';
import { generateAppendices } from './sections/Appendices';

/**
 * Brand Strategy Template
 */
export class BrandStrategyTemplate {
  private metadata: ExportMetadata;

  constructor(
    private data: AggregatedData,
    private brandData: BrandData,
    private options: ExportOptions
  ) {
    this.metadata = this.generateMetadata();
  }

  /**
   * Generate complete markdown document
   */
  generate(): string {
    let markdown = '';

    // Document header
    markdown += this.generateHeader();

    // Table of Contents
    markdown += this.generateTableOfContents();

    // Main sections
    markdown += generateExecutiveSummary(this.data, this.brandData);
    markdown += generateIDEAFramework(this.data, this.brandData);
    markdown += generateCustomerAvatar(this.data, this.brandData);
    markdown += generateBrandCanvas(this.data, this.brandData);

    // Conversation insights (if enabled)
    if (this.options.includeChats) {
      markdown += generateConversationInsights(this.data, this.options);
    }

    // Implementation roadmap
    markdown += this.generateImplementationRoadmap();

    // Appendices
    markdown += generateAppendices(this.data, this.metadata);

    return markdown;
  }

  /**
   * Generate document header
   */
  private generateHeader(): string {
    const companyName = this.brandData.userInfo.company || 'Your Brand';
    const date = md.formatDate(new Date());

    let header = '';
    header += md.heading(`${companyName} - Brand Strategy Documentation`, 1);
    header += md.blockquote(`Generated by IDEA Brand Coach on ${date}`);
    header += md.horizontalRule();

    return header;
  }

  /**
   * Generate table of contents
   */
  private generateTableOfContents(): string {
    const sections: Array<{ title: string; level: number }> = [
      { title: 'Executive Summary', level: 1 },
      { title: 'IDEA Strategic Brand Framework', level: 1 },
      { title: 'Customer Avatar Profile', level: 1 },
      { title: 'Brand Canvas Strategy', level: 1 },
    ];

    if (this.options.includeChats) {
      sections.push({ title: 'AI Conversation Insights', level: 1 });
    }

    sections.push(
      { title: 'Implementation Roadmap', level: 1 },
      { title: 'Appendices', level: 1 }
    );

    let toc = md.heading('Table of Contents', 2);
    toc += md.tableOfContents(sections);
    toc += md.horizontalRule();

    return toc;
  }

  /**
   * Generate implementation roadmap section
   */
  private generateImplementationRoadmap(): string {
    let content = '';

    content += md.heading('Implementation Roadmap', 2);

    // Next steps based on completion
    content += md.heading('Immediate Next Steps', 3);

    const nextSteps = this.determineNextSteps();
    if (nextSteps.length > 0) {
      content += md.orderedList(nextSteps);
    } else {
      content += md.paragraph(
        '🎉 Congratulations! Your brand strategy is complete. ' +
        'Focus on consistent implementation and periodic review.'
      );
    }

    // Implementation guidelines
    content += md.heading('Content Guidelines', 3);

    const guidelines: string[] = [
      md.bold('Brand Consistency') + ': Ensure all communications reflect your mission and values',
      md.bold('Maintain Consistent Tone') + ': Use your brand voice across all touchpoints',
      md.bold('Content Strategy') + ': Create content that reinforces your value proposition',
      md.bold('Align Messaging') + ': Keep messaging consistent with your brand personality traits',
      md.bold('Team Alignment') + ': Share this brand canvas with all team members',
      md.bold('Regular Review') + ': Update quarterly to ensure relevance and accuracy',
    ];

    content += md.unorderedList(guidelines);

    content += md.horizontalRule();

    return content;
  }

  /**
   * Determine next steps based on completion status
   */
  private determineNextSteps(): string[] {
    const steps: string[] = [];
    const stats = this.data.metadata.completionStats;

    // Check each section
    if ((stats.insight || 0) < 100) {
      steps.push('Complete the IDEA Framework Insight module to define your market and consumer insights');
    }

    if ((stats.distinctive || 0) < 100) {
      steps.push('Complete the IDEA Framework Distinctive module to clarify your unique value proposition');
    }

    if ((stats.empathy || 0) < 100) {
      steps.push('Complete the IDEA Framework Empathy module to strengthen emotional connections');
    }

    if ((stats.authentic || 0) < 100) {
      steps.push('Complete the IDEA Framework Authentic module to define your brand values and story');
    }

    if ((stats.avatar || 0) < 100) {
      steps.push('Complete the Avatar Builder to create a detailed customer profile');
    }

    if ((stats.canvas || 0) < 100) {
      steps.push('Complete the Brand Canvas to finalize all core brand elements');
    }

    // If everything is complete, suggest next tools
    if (steps.length === 0) {
      steps.push('Use the Brand Copy Generator to create brand-aligned content');
      steps.push('Develop a content calendar based on your brand voice and personality');
      steps.push('Create brand guidelines document for team and contractors');
    }

    return steps;
  }

  /**
   * Generate metadata for export
   */
  private generateMetadata(): ExportMetadata {
    const totalKnowledge = this.data.metadata.totalEntries;
    const totalSessions = this.data.chatSessions.length;
    const totalMessages = this.data.chatSessions.reduce(
      (sum, session) => sum + session.messages.length,
      0
    );

    // Calculate overall completion
    const completionStats = Object.values(this.data.metadata.completionStats);
    const avgCompletion = completionStats.length > 0
      ? Math.round(
          completionStats.reduce((sum, val) => sum + val, 0) / completionStats.length
        )
      : 0;

    return {
      exportVersion: EXPORT_SCHEMA_VERSION,
      generatedAt: new Date(),
      userId: this.brandData.userInfo.userId,
      dataSources: {
        knowledgeEntries: totalKnowledge,
        chatSessions: totalSessions,
        chatMessages: totalMessages,
        completionPercentage: avgCompletion,
      },
    };
  }
}
