/* eslint-disable */
// @generated by `npm run evals` (src/mcp/evals/run.ts). DO NOT EDIT BY HAND.
// The MCP evals suite scores and compares coach configurations (skill set × tool grounding)
// and the current coach's user-value KPIs. Re-run `npm run evals` to refresh.
import type { EvalReport } from '@/mcp/evals/types';

export const EVAL_REPORT: EvalReport = {
  "schemaVersion": 1,
  "generatedNote": "Generated by `npm run evals` (src/mcp/evals/run.ts). Deterministic — re-run to refresh; no timestamp so an unchanged run is a no-op diff.",
  "corpus": {
    "fixtures": 102,
    "journeys": 8,
    "personas": {
      "P1": 52,
      "P2": 50
    },
    "types": {
      "journey": 80,
      "negative": 5,
      "edge": 3,
      "isolation": 2,
      "uniqueness": 12
    },
    "uniqueToolLabels": 11,
    "uniqueSkillPaths": 105,
    "oracleDims": {
      "skill-faithful": 102,
      "tool-call": 102,
      "schema": 102,
      "persona-adapt": 102,
      "artifact": 102,
      "safety": 102
    }
  },
  "configs": [
    {
      "id": "book-grounding",
      "label": "Book grounding (baseline)",
      "description": "Tools grounded only in the 158-skill book corpus (skills/idea/framework). The pre-existing baseline before the App Skill Architecture.",
      "groundingSource": "book",
      "current": false,
      "metrics": [
        {
          "id": "tool-grounding-coverage",
          "label": "Tool grounding coverage",
          "description": "How many coach tools this config grounds in authored skills.",
          "value": 0.8,
          "display": "4 tools",
          "weight": 0.2,
          "detail": "build_avatar_stage, generate_concepts, run_diagnostic_evidence, run_trust_gap"
        },
        {
          "id": "grounding-density",
          "label": "Grounding density",
          "description": "Average number of grounding skills per grounded tool.",
          "value": 1,
          "display": "22.8 skills/tool",
          "weight": 0.15
        },
        {
          "id": "skill-resolution",
          "label": "Corpus skill resolution",
          "description": "Share of skills the golden corpus cites that resolve in this config.",
          "value": 0.9619047619047619,
          "display": "101 / 105",
          "weight": 0.3
        },
        {
          "id": "guardrail-strength",
          "label": "Guardrail enforcement",
          "description": "Whether the config injects the hard-rule guardrail (no buyer-state leak) into grounded tool descriptions.",
          "value": 0,
          "display": "Not enforced",
          "weight": 0.2
        },
        {
          "id": "architecture-integrity",
          "label": "Architecture integrity",
          "description": "Tier completeness, always-in-context set, internal-only set, dependency + tier sizes.",
          "value": 0,
          "display": "0 / 5 checks",
          "weight": 0.15
        }
      ],
      "composite": 0.5985714285714286,
      "grade": "C"
    },
    {
      "id": "app-skills",
      "label": "App Skill Architecture only",
      "description": "Tools grounded only in the 20-skill App Skill Architecture (IDEA-APP-SKILLS-001 v1.0) — the operational spec without the book knowledge corpus underneath.",
      "groundingSource": "app",
      "current": false,
      "metrics": [
        {
          "id": "tool-grounding-coverage",
          "label": "Tool grounding coverage",
          "description": "How many coach tools this config grounds in authored skills.",
          "value": 1,
          "display": "5 tools",
          "weight": 0.2,
          "detail": "build_avatar_stage, generate_brief, generate_concepts, run_diagnostic_evidence, run_trust_gap"
        },
        {
          "id": "grounding-density",
          "label": "Grounding density",
          "description": "Average number of grounding skills per grounded tool.",
          "value": 0.43333333333333335,
          "display": "2.6 skills/tool",
          "weight": 0.15
        },
        {
          "id": "skill-resolution",
          "label": "Corpus skill resolution",
          "description": "Share of skills the golden corpus cites that resolve in this config.",
          "value": 0,
          "display": "0 / 105",
          "weight": 0.3,
          "detail": "App-skills alone do not cover the book paths the corpus cites — they are the operational layer, not the knowledge corpus."
        },
        {
          "id": "guardrail-strength",
          "label": "Guardrail enforcement",
          "description": "Whether the config injects the hard-rule guardrail (no buyer-state leak) into grounded tool descriptions.",
          "value": 1,
          "display": "Enforced",
          "weight": 0.2
        },
        {
          "id": "architecture-integrity",
          "label": "Architecture integrity",
          "description": "Tier completeness, always-in-context set, internal-only set, dependency + tier sizes.",
          "value": 1,
          "display": "5 / 5 checks",
          "weight": 0.15
        }
      ],
      "composite": 0.615,
      "grade": "C"
    },
    {
      "id": "app+book",
      "label": "App Skills + Book (current)",
      "description": "Tools grounded in both layers — the operational App Skill Architecture over the book knowledge corpus. This is the configuration the live coach runs.",
      "groundingSource": "both",
      "current": true,
      "metrics": [
        {
          "id": "tool-grounding-coverage",
          "label": "Tool grounding coverage",
          "description": "How many coach tools this config grounds in authored skills.",
          "value": 1,
          "display": "5 tools",
          "weight": 0.2,
          "detail": "build_avatar_stage, generate_brief, generate_concepts, run_diagnostic_evidence, run_trust_gap"
        },
        {
          "id": "grounding-density",
          "label": "Grounding density",
          "description": "Average number of grounding skills per grounded tool.",
          "value": 1,
          "display": "20.8 skills/tool",
          "weight": 0.15
        },
        {
          "id": "skill-resolution",
          "label": "Corpus skill resolution",
          "description": "Share of skills the golden corpus cites that resolve in this config.",
          "value": 0.9619047619047619,
          "display": "101 / 105",
          "weight": 0.3
        },
        {
          "id": "guardrail-strength",
          "label": "Guardrail enforcement",
          "description": "Whether the config injects the hard-rule guardrail (no buyer-state leak) into grounded tool descriptions.",
          "value": 1,
          "display": "Enforced",
          "weight": 0.2
        },
        {
          "id": "architecture-integrity",
          "label": "Architecture integrity",
          "description": "Tier completeness, always-in-context set, internal-only set, dependency + tier sizes.",
          "value": 1,
          "display": "5 / 5 checks",
          "weight": 0.15
        }
      ],
      "composite": 0.9885714285714285,
      "grade": "A"
    }
  ],
  "currentConfigId": "app+book",
  "coachValue": [
    {
      "id": "skill-faithfulness",
      "label": "Skill faithfulness",
      "description": "Fixtures whose claims are traced to a cited skill.",
      "value": 1,
      "display": "100%",
      "category": "grounding"
    },
    {
      "id": "tool-call-coverage",
      "label": "Tool-call coverage",
      "description": "Fixtures asserting the exact tool sequence invoked.",
      "value": 1,
      "display": "100%",
      "category": "grounding"
    },
    {
      "id": "persona-adaptation",
      "label": "Persona adaptation",
      "description": "Fixtures asserting persona-specific coaching behaviour.",
      "value": 1,
      "display": "100%",
      "category": "persona"
    },
    {
      "id": "persona-balance",
      "label": "Persona balance",
      "description": "Balance of the two ICPs across the corpus (P1 vs P2).",
      "value": 0.9803921568627451,
      "display": "P1 52 · P2 50",
      "category": "persona"
    },
    {
      "id": "safety-coverage",
      "label": "Safety coverage",
      "description": "Fixtures carrying a safety/isolation oracle.",
      "value": 1,
      "display": "100%",
      "category": "safety"
    },
    {
      "id": "hardening-cases",
      "label": "Hardening cases",
      "description": "Edge / negative / isolation scenarios present (target 10).",
      "value": 1,
      "display": "10 cases",
      "category": "safety"
    },
    {
      "id": "actionability",
      "label": "Actionability",
      "description": "Journey fixtures ending on an actionable deliverable (score / trigger / brief / test).",
      "value": 0.8375,
      "display": "84%",
      "category": "actionability",
      "detail": "Trevor’s governing promise: every session ends with something to act on."
    },
    {
      "id": "artifact-coverage",
      "label": "Artifact coverage",
      "description": "Fixtures that produce a concrete artifact.",
      "value": 1,
      "display": "100%",
      "category": "actionability"
    },
    {
      "id": "journey-coverage",
      "label": "Journey coverage",
      "description": "Journeys exercised with both ICPs present.",
      "value": 1,
      "display": "8 / 8 journeys",
      "category": "coverage"
    },
    {
      "id": "tool-surface-reach",
      "label": "Tool-surface reach",
      "description": "Corpus-exercised tools that are skill-grounded in the live coach.",
      "value": 0.45454545454545453,
      "display": "5 / 11 tools",
      "category": "coverage",
      "detail": "Remaining labels are planned/aliased tools not yet grounded."
    }
  ],
  "coachValueScore": 0.9272437611408201,
  "guardrails": [
    {
      "id": "gr-buyer-state-rule",
      "label": "Buyer-state names (Tier B) kept out of primary panels",
      "passed": true,
      "detail": "Per IDEA-POLICY-TERM-001: buyer-state names are Tier B — opt-in expansion panels only, never the primary output."
    },
    {
      "id": "gr-tier-a-commercial",
      "label": "Tier A commercial terms always present (terminology policy)",
      "passed": true,
      "detail": "Trust Gap™ / Decision Trigger™ / pillar names appear across all surfaces incl. app UI — the Distinctive pillar applied to our own vocabulary."
    },
    {
      "id": "gr-internal-only-set",
      "label": "Engine-only skills flagged internal (05 + Tier 4)",
      "passed": true,
      "detail": "internal-only = 05, 15, 16, 17, 18, 19, 20"
    },
    {
      "id": "gr-grounding-injects-rule",
      "label": "Grounded tools carry the guardrail reminder",
      "passed": true,
      "detail": "appGroundingPreamble reasserts the buyer-state internal rule in tool descriptions."
    },
    {
      "id": "gr-component0-clean",
      "label": "Component 0 examples contain no buyer-state names",
      "passed": true,
      "detail": "Skill 06 primary-conversion-problem examples are plain-language only."
    },
    {
      "id": "gr-jtbd-retired",
      "label": "Jobs-to-be-done retired in favour of Purchase Motivation",
      "passed": true,
      "detail": "Skill 08 explicitly retires JTBD."
    },
    {
      "id": "gr-tier1-not-internal",
      "label": "Always-in-context (Tier 1) skills are not engine-only",
      "passed": true,
      "detail": "Tier-1 foundation skills shape user-facing output; none are internal-only."
    }
  ],
  "flags": [
    "The master-architecture header states '14 Alpha skills · 6 Beta skills' but the per-skill scope table yields 17 Alpha / 3 Beta (Beta = 11, 13, 14). This manifest follows the granular per-skill table. DISCREPANCY to confirm with Trevor.",
    "Corpus tool labels not yet skill-grounded (planned/aliased): design_test, draft_asset, generate_signature, publish_filter_check, run_conversation, search_user_kb.",
    "App skills awaiting Trevor's detailed doc (content_fidelity ≠ full): 11, 12, 13, 14, 15, 16, 17, 18, 19, 20.",
    "Live LLM tier is gated (BRAND_COACH_MCP_HOST=1 + ANTHROPIC_API_KEY). Deterministic core runs without it."
  ],
  "liveTier": {
    "available": false,
    "reason": "Server-contract checks ran against the in-process MCP server. LLM behavioural tier gated (set ANTHROPIC_API_KEY + BRAND_COACH_MCP_HOST=1, then `npm run evals:live`).",
    "metrics": [
      {
        "id": "live-tool-availability",
        "label": "Tool availability",
        "description": "Corpus-exercised tools the live server actually advertises.",
        "value": 0.8181818181818182,
        "display": "9 / 11",
        "weight": 0,
        "detail": "Advertised tools: 43."
      },
      {
        "id": "live-grounding-reach",
        "label": "Grounding reach (live)",
        "description": "Grounded tools whose live description carries a skill-grounding citation.",
        "value": 1,
        "display": "5 / 5",
        "weight": 0
      },
      {
        "id": "live-guardrail-surface",
        "label": "Guardrail in tool surface (live)",
        "description": "Grounded tools whose live description carries the buyer-state internal-only rule.",
        "value": 1,
        "display": "5 / 5",
        "weight": 0,
        "detail": "Proves the App Skill Architecture hard rule reaches the model-facing tool surface."
      }
    ]
  }
};
