/**
 * Avatar Types
 *
 * Type definitions for customer avatar management.
 * These types define the data structures for customer personas used in brand consulting.
 */

/**
 * Demographics data for an avatar.
 * Represents the statistical characteristics of the target customer.
 */
export interface AvatarDemographics {
  /** Age range (e.g., '25-34', '35-44') */
  age?: string;

  /** Income level (e.g., '$75k-100k', '$100k-150k') */
  income?: string;

  /** Location type (e.g., 'urban', 'suburban', 'rural') */
  location?: string;

  /** Text description of lifestyle and daily routines */
  lifestyle?: string;
}

/**
 * Psychographics data for an avatar.
 * Represents the psychological characteristics and emotional drivers of the target customer.
 */
export interface AvatarPsychographics {
  /** Array of core values (e.g., ['sustainability', 'quality', 'family']) */
  values?: string[];

  /** Array of primary fears (e.g., ['missing out', 'wasting money', 'poor quality']) */
  fears?: string[];

  /** Array of deep desires (e.g., ['status', 'belonging', 'achievement']) */
  desires?: string[];

  /** Array of emotional triggers (e.g., ['scarcity', 'social proof', 'authority']) */
  triggers?: string[];
}

/**
 * Buying behavior data for an avatar.
 * Represents the purchasing patterns and decision-making process of the target customer.
 */
export interface AvatarBuyingBehavior {
  /** Buying intent level (e.g., 'high', 'medium', 'low', 'researching') */
  intent?: string;

  /** Array of decision factors (e.g., ['price', 'quality', 'reviews', 'brand reputation']) */
  decision_factors?: string[];

  /** Shopping style preference (e.g., 'impulse buyer', 'researcher', 'brand loyal') */
  shopping_style?: string;

  /** Price sensitivity level (e.g., 'high', 'medium', 'low') */
  price_consciousness?: string;
}

/**
 * Avatar metadata for UI customization and tracking.
 * Used for tab navigation and visual distinction.
 */
export interface AvatarMetadata {
  /** Color theme for the avatar tab */
  color?: string;

  /** Icon identifier for the avatar tab */
  icon?: string;

  /** Brief description of the avatar */
  description?: string;

  /** Additional custom metadata */
  [key: string]: any;
}

/**
 * Avatar completion status tracking.
 * Used to display progress in the multi-avatar UI.
 */
export interface AvatarCompletionStatus {
  /** Overall completion percentage (0-100) */
  percentage: number;

  /** Number of fields that have been filled */
  filledFields: number;

  /** Total number of fields in the avatar */
  totalFields: number;

  /** Completion percentages by section */
  sectionCompletions?: {
    demographics: number;
    psychographics: number;
    behavior: number;
    voice: number;
  };
}

/**
 * Complete avatar entity with all metadata.
 * Represents a customer persona used for brand strategy and marketing.
 */
export interface Avatar {
  /** Unique identifier for the avatar */
  id: string;

  /** ID of the user who owns this avatar */
  user_id: string;

  /** Display name for the avatar */
  name: string;

  /** Optional description or summary of the avatar */
  description?: string | null;

  /** Demographic characteristics */
  demographics?: AvatarDemographics;

  /** Psychographic characteristics */
  psychographics?: AvatarPsychographics;

  /** Buying behavior patterns */
  buying_behavior?: AvatarBuyingBehavior;

  /** Raw customer feedback or voice of customer data */
  voice_of_customer?: string | null;

  /** Whether this avatar is a template (e.g., 'Weekend Warrior', 'Budget Conscious') */
  is_template: boolean;

  /** Overall completion percentage for multi-avatar tracking (0-100) */
  completion_percentage: number;

  /** ISO 8601 timestamp when avatar was created */
  created_at: string;

  /** ISO 8601 timestamp when avatar was last updated */
  updated_at: string;

  /** ISO 8601 timestamp when avatar was last accessed (for tab sorting) */
  last_accessed_at?: string;

  /** UI metadata for tab customization */
  metadata?: AvatarMetadata;
}

/**
 * Data required to create a new avatar.
 * Used when creating avatars via the avatar service.
 * ID, user_id, and timestamps are generated by the service.
 */
export interface AvatarCreate {
  /** Display name for the avatar */
  name: string;

  /** Optional description or summary of the avatar */
  description?: string;

  /** Demographic characteristics */
  demographics?: AvatarDemographics;

  /** Psychographic characteristics */
  psychographics?: AvatarPsychographics;

  /** Buying behavior patterns */
  buying_behavior?: AvatarBuyingBehavior;

  /** Raw customer feedback or voice of customer data */
  voice_of_customer?: string;

  /** Whether this avatar is a template (defaults to false) */
  is_template?: boolean;

  /** UI metadata for tab customization */
  metadata?: AvatarMetadata;
}

/**
 * Data for updating an existing avatar.
 * All fields are optional - only provided fields will be updated.
 */
export interface AvatarUpdate {
  /** Updated display name */
  name?: string;

  /** Updated description */
  description?: string | null;

  /** Updated demographic characteristics */
  demographics?: AvatarDemographics;

  /** Updated psychographic characteristics */
  psychographics?: AvatarPsychographics;

  /** Updated buying behavior patterns */
  buying_behavior?: AvatarBuyingBehavior;

  /** Updated customer feedback */
  voice_of_customer?: string | null;

  /** Updated template status */
  is_template?: boolean;

  /** Updated completion percentage */
  completion_percentage?: number;

  /** Updated last accessed timestamp */
  last_accessed_at?: string;

  /** Updated UI metadata */
  metadata?: AvatarMetadata;
}