/**
 * Chat Types
 *
 * Type definitions for Brand Coach Chat feature.
 * These types define the data structures used across all chat service implementations.
 */

/**
 * Role of a chat message participant
 * - user: Message from the user
 * - assistant: Message from Brand Coach AI
 * - system: System-generated message (e.g., welcome, instructions)
 */
export type ChatRole = 'user' | 'assistant' | 'system';

/**
 * Type of chatbot for message filtering
 * - idea-framework-consultant: IDEA Framework specialist consultant with RAG
 */
export type ChatbotType = 'idea-framework-consultant';

/**
 * Image attachment metadata for chat messages
 */
export interface ChatImageAttachment {
  /** Unique identifier for the image */
  id: string;
  /** Public URL or signed URL for the image */
  url: string;
  /** Original filename */
  filename: string;
  /** MIME type of the image */
  mime_type?: string;
  /** File size in bytes (after compression if applied) */
  file_size?: number;
  /** Original file size before compression (in bytes) */
  original_file_size?: number;
  /** Compression ratio as percentage (e.g., 60 means 60% smaller) */
  compression_ratio?: number;
  /** Whether compression was applied to this image */
  was_compressed?: boolean;
  /** GPT-4 Vision analysis cache (optional) */
  analysis?: string;
}

/**
 * Metadata that can be attached to chat messages
 */
export interface ChatMessageMetadata {
  /** Optional follow-up question suggestions */
  suggestions?: string[];
  /** Optional source citations */
  sources?: string[];
  /** Optional image attachments */
  images?: ChatImageAttachment[];
  /** Any other metadata */
  [key: string]: any;
}

/**
 * Complete chat message with all metadata.
 * Represents a persisted message in the conversation history.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;

  /** ID of the user who owns this conversation */
  user_id: string;

  /** ID of the chat session this message belongs to */
  session_id?: string;

  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** Type of chatbot this message belongs to */
  chatbot_type?: ChatbotType;

  /** Optional metadata (suggestions, sources, images, etc.) */
  metadata?: ChatMessageMetadata;

  /** ISO 8601 timestamp when message was created */
  created_at: string;

  /** ISO 8601 timestamp when message was last updated */
  updated_at: string;
}

/**
 * Data required to create a new chat message.
 * Used when sending messages to the chat service.
 * ID, user_id, and timestamps are generated by the service.
 */
export interface ChatMessageCreate {
  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** ID of the chat session this message belongs to */
  session_id?: string;

  /** Type of chatbot (defaults to 'idea-framework-consultant') */
  chatbot_type?: ChatbotType;

  /** Optional metadata to attach to the message */
  metadata?: ChatMessageMetadata;
}

/**
 * Data for updating an existing chat message.
 * All fields are optional - only provided fields will be updated.
 */
export interface ChatMessageUpdate {
  /** Updated message content */
  content?: string;

  /** Updated metadata */
  metadata?: ChatMessageMetadata;
}

/**
 * Response from Brand Coach AI.
 * Includes the assistant's message plus optional suggestions and source citations.
 */
export interface ChatResponse {
  /** The assistant's message */
  message: ChatMessage;

  /** Optional follow-up question suggestions */
  suggestions?: string[];

  /** Optional source citations (e.g., IDEA Framework docs) */
  sources?: string[];

  /** Promise that resolves when title generation completes (for cache invalidation) */
  titlePromise?: Promise<void>;
}

/**
 * Type of conversation for filtering
 * - general: Standard Brand Coach conversation
 * - field: Inline field-level chat
 */
export type ConversationType = 'general' | 'field';

/**
 * Chat session representing a conversation thread.
 * Similar to ChatGPT/Claude.ai conversation management.
 */
export interface ChatSession {
  /** Unique identifier for the session */
  id: string;

  /** ID of the user who owns this session */
  user_id: string;

  /** Type of chatbot this session belongs to */
  chatbot_type: ChatbotType;

  /** Title of the session (auto-generated or user-defined) */
  title: string;

  /** Type of conversation: general or field */
  conversation_type: ConversationType;

  /** Field identifier for field-level chats (e.g., 'avatar.demographics') */
  field_id?: string;

  /** Human-readable label for the field */
  field_label?: string;

  /** Page context where conversation started */
  page_context?: string;

  /** ISO 8601 timestamp when session was created */
  created_at: string;

  /** ISO 8601 timestamp when session was last updated */
  updated_at: string;
}

/**
 * Data required to create a new chat session.
 */
export interface ChatSessionCreate {
  /** Type of chatbot (defaults to current chatbot type) */
  chatbot_type?: ChatbotType;

  /** Optional title (defaults to 'New Chat') */
  title?: string;

  /** Type of conversation: general or field (defaults to 'general') */
  conversation_type?: ConversationType;

  /** Field identifier for field-level chats */
  field_id?: string;

  /** Human-readable label for the field */
  field_label?: string;

  /** Page context where conversation started */
  page_context?: string;
}

/**
 * Data for updating an existing chat session.
 */
export interface ChatSessionUpdate {
  /** Updated title */
  title?: string;
}
