/**
 * Chat Types
 *
 * Type definitions for Brand Coach Chat feature.
 * These types define the data structures used across all chat service implementations.
 */

/**
 * Role of a chat message participant
 * - user: Message from the user
 * - assistant: Message from Brand Coach AI
 * - system: System-generated message (e.g., welcome, instructions)
 */
export type ChatRole = 'user' | 'assistant' | 'system';

/**
 * Complete chat message with all metadata.
 * Represents a persisted message in the conversation history.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;

  /** ID of the user who owns this conversation */
  user_id: string;

  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** Optional metadata (suggestions, sources, etc.) */
  metadata?: Record<string, any>;

  /** ISO 8601 timestamp when message was created */
  created_at: string;

  /** ISO 8601 timestamp when message was last updated */
  updated_at: string;
}

/**
 * Data required to create a new chat message.
 * Used when sending messages to the chat service.
 * ID, user_id, and timestamps are generated by the service.
 */
export interface ChatMessageCreate {
  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** Optional metadata to attach to the message */
  metadata?: Record<string, any>;
}

/**
 * Data for updating an existing chat message.
 * All fields are optional - only provided fields will be updated.
 */
export interface ChatMessageUpdate {
  /** Updated message content */
  content?: string;

  /** Updated metadata */
  metadata?: Record<string, any>;
}

/**
 * Response from Brand Coach AI.
 * Includes the assistant's message plus optional suggestions and source citations.
 */
export interface ChatResponse {
  /** The assistant's message */
  message: ChatMessage;

  /** Optional follow-up question suggestions */
  suggestions?: string[];

  /** Optional source citations (e.g., IDEA Framework docs) */
  sources?: string[];
}
