/**
 * Chat Types
 *
 * Type definitions for Brand Coach Chat feature.
 * These types define the data structures used across all chat service implementations.
 */

/**
 * Role of a chat message participant
 * - user: Message from the user
 * - assistant: Message from Brand Coach AI
 * - system: System-generated message (e.g., welcome, instructions)
 */
export type ChatRole = 'user' | 'assistant' | 'system';

/**
 * Type of chatbot for message filtering
 * - brand-coach: General Brand Coach GPT (uses RAG with embeddings)
 * - idea-framework-consultant: IDEA Framework specialist consultant
 */
export type ChatbotType = 'brand-coach' | 'idea-framework-consultant';

/**
 * Complete chat message with all metadata.
 * Represents a persisted message in the conversation history.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;

  /** ID of the user who owns this conversation */
  user_id: string;

  /** ID of the chat session this message belongs to */
  session_id?: string;

  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** Type of chatbot this message belongs to */
  chatbot_type?: ChatbotType;

  /** Optional metadata (suggestions, sources, etc.) */
  metadata?: Record<string, any>;

  /** ISO 8601 timestamp when message was created */
  created_at: string;

  /** ISO 8601 timestamp when message was last updated */
  updated_at: string;
}

/**
 * Data required to create a new chat message.
 * Used when sending messages to the chat service.
 * ID, user_id, and timestamps are generated by the service.
 */
export interface ChatMessageCreate {
  /** Role of the message sender */
  role: ChatRole;

  /** Text content of the message */
  content: string;

  /** ID of the chat session this message belongs to */
  session_id?: string;

  /** Type of chatbot (defaults to 'brand-coach') */
  chatbot_type?: ChatbotType;

  /** Optional metadata to attach to the message */
  metadata?: Record<string, any>;
}

/**
 * Data for updating an existing chat message.
 * All fields are optional - only provided fields will be updated.
 */
export interface ChatMessageUpdate {
  /** Updated message content */
  content?: string;

  /** Updated metadata */
  metadata?: Record<string, any>;
}

/**
 * Response from Brand Coach AI.
 * Includes the assistant's message plus optional suggestions and source citations.
 */
export interface ChatResponse {
  /** The assistant's message */
  message: ChatMessage;

  /** Optional follow-up question suggestions */
  suggestions?: string[];

  /** Optional source citations (e.g., IDEA Framework docs) */
  sources?: string[];

  /** Promise that resolves when title generation completes (for cache invalidation) */
  titlePromise?: Promise<void>;
}

/**
 * Chat session representing a conversation thread.
 * Similar to ChatGPT/Claude.ai conversation management.
 */
export interface ChatSession {
  /** Unique identifier for the session */
  id: string;

  /** ID of the user who owns this session */
  user_id: string;

  /** Type of chatbot this session belongs to */
  chatbot_type: ChatbotType;

  /** Title of the session (auto-generated or user-defined) */
  title: string;

  /** ISO 8601 timestamp when session was created */
  created_at: string;

  /** ISO 8601 timestamp when session was last updated */
  updated_at: string;
}

/**
 * Data required to create a new chat session.
 */
export interface ChatSessionCreate {
  /** Type of chatbot (defaults to current chatbot type) */
  chatbot_type?: ChatbotType;

  /** Optional title (defaults to 'New Chat') */
  title?: string;
}

/**
 * Data for updating an existing chat session.
 */
export interface ChatSessionUpdate {
  /** Updated title */
  title?: string;
}
