/**
 * Field Metadata Types
 * Type definitions for manual field editing with auto-save, validation, and edit source tracking
 * Following SOLID principles and clean architecture patterns
 */

/**
 * Source of a field edit
 * Tracks whether content was manually entered by user or generated by AI
 */
export type EditSource = 'manual' | 'ai';

/**
 * Validation result for a field value
 */
export interface ValidationResult {
  isValid: boolean;
  error?: string;
}

/**
 * Field type for validation and UI rendering
 */
export type FieldType =
  | 'text'
  | 'email'
  | 'url'
  | 'number'
  | 'range'
  | 'textarea'
  | 'richtext';

/**
 * Field validation configuration
 */
export interface FieldValidation {
  type: FieldType;
  required?: boolean;
  minLength?: number;
  maxLength?: number;
  min?: number;
  max?: number;
  pattern?: RegExp;
  customValidator?: (value: string) => ValidationResult;
}

/**
 * Field configuration for the editor
 */
export interface FieldConfig {
  fieldIdentifier: string;
  label: string;
  helpText?: string;
  placeholder?: string;
  validation?: FieldValidation;
  autoSaveDelay?: number; // milliseconds, default 500
}

/**
 * Field edit metadata
 * Tracks information about when and how a field was edited
 */
export interface FieldEditMetadata {
  editSource: EditSource;
  editedAt: Date;
  editedBy?: string; // user ID
  previousValue?: string;
  validationState?: ValidationResult;
}

/**
 * Field history entry
 * Represents a single version in the field's edit history
 */
export interface FieldHistoryEntry {
  id: string;
  value: string;
  metadata: FieldEditMetadata;
  timestamp: Date;
  isCurrentVersion: boolean;
}

/**
 * Field sync state
 * Tracks the synchronization status of a field
 */
export type FieldSyncState = 'saved' | 'saving' | 'unsaved' | 'error';

/**
 * Field editor state
 * Complete state for a field being edited
 */
export interface FieldEditorState {
  value: string;
  isDirty: boolean;
  syncState: FieldSyncState;
  validationResult?: ValidationResult;
  editSource: EditSource;
  lastSavedAt?: Date;
}
