/**
 * Chapter Fields Configuration - Single Source of Truth
 *
 * Centralized configuration for all 11 IDEA framework chapters including:
 * - Chapter metadata (titles, descriptions)
 * - Associated brand data fields
 * - Field types and validation
 * - Field source tracking (AI vs manual)
 *
 * This ensures consistent field mapping across:
 * - ChapterSectionAccordion component
 * - Brand form panels
 * - Data persistence layer
 * - AI coach interactions
 */

/**
 * Field source indicator
 * - 'ai': Generated by AI assistant
 * - 'manual': Manually entered by user
 */
export type FieldSource = 'ai' | 'manual';

/**
 * Chapter completion status
 * - 'completed': Chapter has been finished
 * - 'active': Currently working on this chapter
 * - 'future': Not yet started, locked until previous chapters complete
 */
export type ChapterStatus = 'completed' | 'active' | 'future';

/**
 * Field type determines UI component
 * - 'text': Single-line input
 * - 'textarea': Multi-line textarea
 * - 'array': Array of strings (for lists)
 */
export type FieldType = 'text' | 'textarea' | 'array';

/**
 * Individual field configuration within a chapter
 */
export interface ChapterField {
  /** Unique field identifier (maps to BrandData keys) */
  id: string;

  /** Display label for the field */
  label: string;

  /** Field type (determines UI component) */
  type: FieldType;

  /** Placeholder text for empty fields */
  placeholder: string;

  /** Is this field required to complete the chapter? */
  required: boolean;

  /** Help text or description */
  helpText?: string;

  /** IDEA framework relevance — explains why this field matters in the framework */
  ideaRelevance?: string;
}

/**
 * Chapter configuration
 */
export interface Chapter {
  /** Unique chapter identifier */
  id: string;

  /** Display title */
  title: string;

  /** Short description of chapter purpose */
  description: string;

  /** IDEA framework pillar this chapter belongs to */
  pillar: 'insight' | 'distinctive' | 'empathy' | 'authentic' | 'foundation';

  /** Fields included in this chapter */
  fields: ChapterField[];

  /** Order in the journey (1-11) */
  order: number;
}

/**
 * Complete chapter registry
 * All 11 chapters in the IDEA Strategic Brand Framework™
 */
export const CHAPTER_FIELDS_MAP: Record<string, Chapter> = {
  // ========================================
  // Foundation Chapters (1-2)
  // ========================================

  BRAND_FOUNDATION: {
    id: 'brand-foundation',
    title: 'Brand Foundation',
    description: 'Define your core brand identity and purpose',
    pillar: 'foundation',
    order: 1,
    fields: [
      {
        id: 'brandPurpose',
        label: 'Brand Purpose',
        type: 'textarea',
        placeholder: 'Why does your brand exist beyond making money?',
        required: true,
        helpText: 'Your brand\'s reason for being and the impact you want to make',
        ideaRelevance: 'Defines the "why" — foundation for every brand decision'
      },
      {
        id: 'brandVision',
        label: 'Brand Vision',
        type: 'textarea',
        placeholder: 'What future do you want to create?',
        required: true,
        helpText: 'Your aspirational view of the future you\'re working toward',
        ideaRelevance: 'Sets your brand\'s aspirational north star (Foundation)'
      },
      {
        id: 'brandMission',
        label: 'Brand Mission',
        type: 'textarea',
        placeholder: 'How will you achieve your vision?',
        required: true,
        helpText: 'The practical steps and approach to fulfilling your purpose',
        ideaRelevance: 'Translates purpose into actionable strategy (Foundation)'
      }
    ]
  },

  BRAND_VALUES: {
    id: 'brand-values',
    title: 'Brand Values',
    description: 'Establish the principles that guide your brand',
    pillar: 'foundation',
    order: 2,
    fields: [
      {
        id: 'brandValues',
        label: 'Core Values',
        type: 'array',
        placeholder: 'Enter your brand values (e.g., Innovation, Integrity, Excellence)',
        required: true,
        helpText: 'The fundamental beliefs and principles that guide your brand decisions',
        ideaRelevance: 'Guiding principles that shape all brand behavior (Foundation)'
      },
      {
        id: 'brandStory',
        label: 'Brand Story',
        type: 'textarea',
        placeholder: 'Tell the story of how your brand came to be and what drives you',
        required: true,
        helpText: 'The narrative that connects your past, present, and future',
        ideaRelevance: 'Narrative that makes your brand memorable and relatable (Foundation)'
      },
      {
        id: 'brandPromise',
        label: 'Brand Promise',
        type: 'textarea',
        placeholder: 'What do you promise to deliver to your customers every time?',
        required: true,
        helpText: 'The commitment you make to your customers that sets expectations',
        ideaRelevance: 'The commitment customers can count on (Foundation)'
      }
    ]
  },

  // ========================================
  // Insight-Driven Chapters (3-5)
  // ========================================

  CUSTOMER_AVATAR: {
    id: 'customer-avatar',
    title: 'Customer Avatar',
    description: 'Build detailed profiles of your ideal customers',
    pillar: 'insight',
    order: 3,
    fields: [
      {
        id: 'demographics',
        label: 'Demographics',
        type: 'textarea',
        placeholder: 'Age, gender, income, location, occupation',
        required: true,
        helpText: 'Quantifiable characteristics of your target audience',
        ideaRelevance: 'Data-driven understanding of who you serve (Insight pillar)'
      },
      {
        id: 'psychographics',
        label: 'Psychographics',
        type: 'textarea',
        placeholder: 'Interests, values, lifestyle, personality traits',
        required: true,
        helpText: 'Psychological attributes and lifestyle characteristics',
        ideaRelevance: 'Reveals the deeper motivations behind customer behavior (Insight pillar)'
      },
      {
        id: 'painPoints',
        label: 'Pain Points',
        type: 'array',
        placeholder: 'What challenges or frustrations do they face?',
        required: true,
        helpText: 'The problems your customers are trying to solve',
        ideaRelevance: 'Problems your brand exists to solve (Insight pillar)'
      },
      {
        id: 'goals',
        label: 'Goals & Aspirations',
        type: 'array',
        placeholder: 'What are they trying to achieve?',
        required: true,
        helpText: 'The outcomes and desires that motivate your customers',
        ideaRelevance: 'Aspirations that align your brand with customer success (Insight pillar)'
      }
    ]
  },

  MARKET_INSIGHT: {
    id: 'market-insight',
    title: 'Market Insight',
    description: 'Understand your market landscape and opportunities',
    pillar: 'insight',
    order: 4,
    fields: [
      {
        id: 'marketInsight',
        label: 'Market Analysis',
        type: 'textarea',
        placeholder: 'What trends, gaps, and opportunities exist in your market?',
        required: true,
        helpText: 'Key market dynamics, trends, and competitive landscape',
        ideaRelevance: 'Market intelligence that informs strategic positioning (Insight pillar)'
      },
      {
        id: 'consumerInsight',
        label: 'Consumer Behavior',
        type: 'textarea',
        placeholder: 'What drives your customers\' decisions and behaviors?',
        required: true,
        helpText: 'Deep understanding of customer motivations and decision-making',
        ideaRelevance: 'Behavioral patterns that shape your brand messaging (Insight pillar)'
      }
    ]
  },

  BUYER_INTENT: {
    id: 'buyer-intent',
    title: 'Buyer Intent',
    description: 'Map the four moments of buyer intent',
    pillar: 'insight',
    order: 5,
    fields: [
      {
        id: 'functionalIntent',
        label: 'Functional Intent',
        type: 'textarea',
        placeholder: 'What practical problem are they solving?',
        required: true,
        helpText: 'The rational, functional reasons for purchase',
        ideaRelevance: 'The practical "what" behind purchase decisions (Insight pillar)'
      },
      {
        id: 'emotionalIntent',
        label: 'Emotional Intent',
        type: 'textarea',
        placeholder: 'How do they want to feel?',
        required: true,
        helpText: 'The emotional outcomes they seek',
        ideaRelevance: 'The feeling customers chase when choosing your brand (Insight pillar)'
      },
      {
        id: 'identityIntent',
        label: 'Identity Intent',
        type: 'textarea',
        placeholder: 'Who do they want to become?',
        required: true,
        helpText: 'The identity transformation they desire',
        ideaRelevance: 'The aspirational self your brand helps customers become (Insight pillar)'
      },
      {
        id: 'socialIntent',
        label: 'Social Intent',
        type: 'textarea',
        placeholder: 'How do they want to be perceived?',
        required: true,
        helpText: 'The social signals and status they seek',
        ideaRelevance: 'The social currency your brand provides (Insight pillar)'
      }
    ]
  },

  // ========================================
  // Distinctive/Different Chapters (6-7)
  // ========================================

  POSITIONING: {
    id: 'positioning',
    title: 'Brand Positioning',
    description: 'Define your unique position in the market',
    pillar: 'distinctive',
    order: 6,
    fields: [
      {
        id: 'positioningStatement',
        label: 'Positioning Statement',
        type: 'textarea',
        placeholder: 'For [target], [brand] is the [category] that [unique benefit] because [reason to believe]',
        required: true,
        helpText: 'A clear statement of how you want to be perceived vs. competitors',
        ideaRelevance: 'How you stand apart in the market (Distinctive pillar)'
      },
      {
        id: 'uniqueValue',
        label: 'Unique Value Proposition',
        type: 'textarea',
        placeholder: 'What makes you uniquely valuable to your customers?',
        required: true,
        helpText: 'The specific value only you can deliver',
        ideaRelevance: 'The one thing only your brand can deliver (Distinctive pillar)'
      },
      {
        id: 'differentiators',
        label: 'Key Differentiators',
        type: 'array',
        placeholder: 'What sets you apart from competitors?',
        required: true,
        helpText: 'Specific advantages that distinguish you in the market',
        ideaRelevance: 'Competitive advantages that make you unmistakable (Distinctive pillar)'
      }
    ]
  },

  BRAND_PERSONALITY: {
    id: 'brand-personality',
    title: 'Brand Personality & Voice',
    description: 'Define how your brand looks, sounds, and feels',
    pillar: 'distinctive',
    order: 7,
    fields: [
      {
        id: 'brandPersonality',
        label: 'Personality Traits',
        type: 'array',
        placeholder: 'Describe your brand as if it were a person (e.g., Bold, Innovative, Caring)',
        required: true,
        helpText: 'Human characteristics that define your brand\'s character',
        ideaRelevance: 'Human traits that make your brand relatable (Distinctive pillar)'
      },
      {
        id: 'brandVoice',
        label: 'Brand Voice',
        type: 'textarea',
        placeholder: 'How does your brand communicate? (tone, style, language)',
        required: true,
        helpText: 'The consistent way you express your brand through words',
        ideaRelevance: 'Consistent tone that builds recognition across channels (Distinctive pillar)'
      },
      {
        id: 'brandArchetype',
        label: 'Brand Archetype',
        type: 'text',
        placeholder: 'Which archetype best represents your brand? (e.g., Hero, Sage, Creator)',
        required: false,
        helpText: 'The universal character pattern your brand embodies',
        ideaRelevance: 'Universal story pattern that deepens brand resonance (Distinctive pillar)'
      }
    ]
  },

  // ========================================
  // Emotionally Intelligent Chapters (8-9)
  // ========================================

  EMOTIONAL_CONNECTION: {
    id: 'emotional-connection',
    title: 'Emotional Connection',
    description: 'Build deep emotional bonds with your audience',
    pillar: 'empathy',
    order: 8,
    fields: [
      {
        id: 'emotionalConnection',
        label: 'Emotional Hook',
        type: 'textarea',
        placeholder: 'What emotion do you want to evoke in your customers?',
        required: true,
        helpText: 'The primary emotional response you aim to create',
        ideaRelevance: 'Creates the emotional bond that drives loyalty (Empathy pillar)'
      },
      {
        id: 'emotionalTriggers',
        label: 'Emotional Triggers',
        type: 'array',
        placeholder: 'What specific triggers activate emotional responses?',
        required: true,
        helpText: 'Specific moments or messages that resonate emotionally',
        ideaRelevance: 'Moments that spark emotional connection with your audience (Empathy pillar)'
      },
      {
        id: 'customerNeeds',
        label: 'Deep Customer Needs',
        type: 'array',
        placeholder: 'What underlying needs are you fulfilling?',
        required: true,
        helpText: 'The fundamental human needs your brand addresses',
        ideaRelevance: 'Unspoken needs your brand fulfills at a human level (Empathy pillar)'
      }
    ]
  },

  CUSTOMER_EXPERIENCE: {
    id: 'customer-experience',
    title: 'Customer Experience',
    description: 'Design meaningful customer interactions',
    pillar: 'empathy',
    order: 9,
    fields: [
      {
        id: 'customerJourney',
        label: 'Customer Journey',
        type: 'textarea',
        placeholder: 'Map the key touchpoints in your customer experience',
        required: true,
        helpText: 'The path customers take from awareness to advocacy',
        ideaRelevance: 'Maps every touchpoint where empathy shapes the experience (Empathy pillar)'
      },
      {
        id: 'experiencePillars',
        label: 'Experience Pillars',
        type: 'array',
        placeholder: 'What are the core elements of your customer experience?',
        required: true,
        helpText: 'The foundational components that shape customer interactions',
        ideaRelevance: 'Core principles that ensure consistent, empathetic interactions (Empathy pillar)'
      },
      {
        id: 'preferredChannels',
        label: 'Preferred Channels',
        type: 'array',
        placeholder: 'Where do your customers want to engage with you?',
        required: true,
        helpText: 'The platforms and channels your audience prefers',
        ideaRelevance: 'Meeting customers where they are builds genuine connection (Empathy pillar)'
      }
    ]
  },

  // ========================================
  // Authoritative & Authentic Chapters (10-11)
  // ========================================

  BRAND_AUTHORITY: {
    id: 'brand-authority',
    title: 'Brand Authority',
    description: 'Establish credibility and thought leadership',
    pillar: 'authentic',
    order: 10,
    fields: [
      {
        id: 'expertise',
        label: 'Areas of Expertise',
        type: 'array',
        placeholder: 'What are you uniquely qualified to speak about?',
        required: true,
        helpText: 'The specific domains where you have deep knowledge and credibility',
        ideaRelevance: 'Domains where your brand has earned the right to lead (Authentic pillar)'
      },
      {
        id: 'credibilityMarkers',
        label: 'Credibility Markers',
        type: 'array',
        placeholder: 'What proves your authority? (awards, certifications, results, testimonials)',
        required: true,
        helpText: 'Evidence that validates your expertise and reliability',
        ideaRelevance: 'Proof points that back up your brand claims (Authentic pillar)'
      },
      {
        id: 'thoughtLeadership',
        label: 'Thought Leadership',
        type: 'textarea',
        placeholder: 'What unique perspectives or insights do you bring to your industry?',
        required: false,
        helpText: 'Your distinctive point of view that shapes industry conversations',
        ideaRelevance: 'Unique perspective that positions you as an industry voice (Authentic pillar)'
      }
    ]
  },

  BRAND_AUTHENTICITY: {
    id: 'brand-authenticity',
    title: 'Brand Authenticity',
    description: 'Express your genuine self and build trust',
    pillar: 'authentic',
    order: 11,
    fields: [
      {
        id: 'authenticityPrinciples',
        label: 'Authenticity Principles',
        type: 'array',
        placeholder: 'What makes your brand genuinely you?',
        required: true,
        helpText: 'The core truths that make your brand real and believable',
        ideaRelevance: 'Builds trust through genuine self-expression (Authentic pillar)'
      },
      {
        id: 'transparency',
        label: 'Transparency Commitment',
        type: 'textarea',
        placeholder: 'How will you be transparent with your customers?',
        required: true,
        helpText: 'Your approach to open, honest communication',
        ideaRelevance: 'Openness that earns long-term customer trust (Authentic pillar)'
      },
      {
        id: 'socialProof',
        label: 'Social Proof',
        type: 'array',
        placeholder: 'What evidence shows you deliver on your promises?',
        required: true,
        helpText: 'Customer stories, results, and validation that build trust',
        ideaRelevance: 'Real results that validate your brand authentically (Authentic pillar)'
      },
      {
        id: 'brandConsistency',
        label: 'Brand Consistency',
        type: 'textarea',
        placeholder: 'How will you ensure consistent brand experiences?',
        required: false,
        helpText: 'Your strategy for maintaining coherence across all touchpoints',
        ideaRelevance: 'Consistency across touchpoints reinforces authenticity (Authentic pillar)'
      }
    ]
  }
};

/**
 * Maps book chapter number (1–11) to the CHAPTER_FIELDS_MAP key.
 * Single source of truth — replaces inline copies in BrandCoachV2.tsx.
 */
export const BOOK_CHAPTER_NUMBER_TO_FIELDS_KEY: Record<number, string> = {
  1: 'BRAND_FOUNDATION',  2: 'BRAND_VALUES',        3: 'CUSTOMER_AVATAR',
  4: 'MARKET_INSIGHT',    5: 'BUYER_INTENT',         6: 'POSITIONING',
  7: 'BRAND_PERSONALITY', 8: 'EMOTIONAL_CONNECTION', 9: 'CUSTOMER_EXPERIENCE',
  10: 'BRAND_AUTHORITY',  11: 'BRAND_AUTHENTICITY',
};

/**
 * Get chapters in order
 */
export function getChaptersInOrder(): Chapter[] {
  return Object.values(CHAPTER_FIELDS_MAP).sort((a, b) => a.order - b.order);
}

/**
 * Get chapter by ID
 */
export function getChapterById(id: string): Chapter | undefined {
  return CHAPTER_FIELDS_MAP[id.toUpperCase().replace(/-/g, '_')];
}

/**
 * Get chapters by pillar
 */
export function getChaptersByPillar(pillar: Chapter['pillar']): Chapter[] {
  return Object.values(CHAPTER_FIELDS_MAP)
    .filter(chapter => chapter.pillar === pillar)
    .sort((a, b) => a.order - b.order);
}

/**
 * Get total field count across all chapters
 */
export function getTotalFieldCount(): number {
  return Object.values(CHAPTER_FIELDS_MAP).reduce(
    (total, chapter) => total + chapter.fields.length,
    0
  );
}

/**
 * Get required field count for a chapter
 */
export function getRequiredFieldCount(chapterId: string): number {
  const chapter = getChapterById(chapterId);
  if (!chapter) return 0;
  return chapter.fields.filter(field => field.required).length;
}

/**
 * Get the chapter that contains a given field
 */
export function getChapterForField(fieldId: string): Chapter | undefined {
  for (const chapter of Object.values(CHAPTER_FIELDS_MAP)) {
    if (chapter.fields.some(f => f.id === fieldId)) return chapter;
  }
  return undefined;
}

/**
 * Get IDEA framework relevance string for a field
 */
export function getFieldIdeaRelevance(fieldId: string): string | undefined {
  for (const chapter of Object.values(CHAPTER_FIELDS_MAP)) {
    const field = chapter.fields.find(f => f.id === fieldId);
    if (field?.ideaRelevance) return field.ideaRelevance;
  }
  return undefined;
}
