/**
 * Brand Canvas PDF Export Component
 *
 * Generates a professional PDF brand strategy document using AI.
 * Uses the same AI-generated content as the markdown export for consistency.
 */

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { useBrand } from '@/contexts/BrandContext';
import { DesktopOnlyFeature } from '@/components/DesktopOnlyFeature';
import { MarkdownExportService } from '@/components/export/MarkdownExportService';
import { MarkdownPDFExporter } from '@/components/export/MarkdownPDFExporter';
import { KnowledgeBaseFactory } from '@/lib/knowledge-base';
import { SupabaseChatService } from '@/services/SupabaseChatService';

interface BrandCanvasData {
  brandPurpose: string;
  brandVision: string;
  brandMission: string;
  brandValues: string[];
  positioningStatement: string;
  valueProposition: string;
  brandPersonality: string[];
  brandVoice: string;
}

interface BrandCanvasPDFExportProps {
  brandCanvas: BrandCanvasData;
  companyName?: string;
}

/**
 * PDF Exporter that converts AI-generated markdown to PDF
 */
class BrandStrategyPDFExporter extends MarkdownPDFExporter {
  private markdownContent: string;
  private exportFilename: string;

  constructor(markdown: string, companyName: string) {
    super({
      title: 'Brand Strategy Document',
      subtitle: companyName,
      primaryColor: [30, 64, 175],
      footerText: 'Generated by IDEA Brand Coach',
    });
    this.markdownContent = markdown;
    this.exportFilename = `${companyName.replace(/\s+/g, '-').toLowerCase()}-brand-strategy.pdf`;
  }

  protected generateMarkdown(): string {
    return this.markdownContent;
  }

  protected getFilename(): string {
    return this.exportFilename;
  }
}

export const BrandCanvasPDFExport: React.FC<BrandCanvasPDFExportProps> = ({
  brandCanvas,
  companyName = "Your Brand"
}) => {
  const { toast } = useToast();
  const { user } = useAuth();
  const { brandData } = useBrand();
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async (): Promise<void> => {
    if (!user) {
      toast({
        title: 'Authentication Required',
        description: 'Please sign in to export your brand strategy.',
        variant: 'destructive',
      });
      return;
    }

    setIsExporting(true);

    try {
      // Update brandData with current user ID
      const exportBrandData = {
        ...brandData,
        userInfo: {
          ...brandData.userInfo,
          userId: user.id,
          email: user.email || brandData.userInfo.email,
        },
      };

      // Initialize services
      const knowledgeRepo = await KnowledgeBaseFactory.createRepository();
      const chatService = new SupabaseChatService();
      const exportService = new MarkdownExportService(
        knowledgeRepo,
        chatService,
        exportBrandData
      );

      // Generate AI-powered markdown content - include up to 10 recent conversations
      const result = await exportService.generateExport({
        includeChats: true,
        maxChatExcerpts: 10,
        format: 'full',
      });

      if (!result.success || !result.markdown) {
        throw result.error || new Error('Failed to generate document');
      }

      // Convert markdown to PDF
      const pdfExporter = new BrandStrategyPDFExporter(
        result.markdown,
        companyName
      );
      await pdfExporter.export();

      toast({
        title: "PDF Generated Successfully",
        description: "Your brand strategy document has been downloaded.",
      });

    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: "Export Error",
        description: error instanceof Error ? error.message : "There was an error generating the PDF. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsExporting(false);
    }
  };

  const mobileAlternative = (
    <div className="text-center p-4 bg-muted/30 rounded-lg">
      <p className="text-sm text-muted-foreground">
        PDF export is available on desktop. Access your account on a computer to download your brand strategy.
      </p>
    </div>
  );

  return (
    <DesktopOnlyFeature
      featureName="Brand Strategy PDF Export"
      mobileAlternative={mobileAlternative}
    >
      <Button
        onClick={handleExport}
        variant="outline"
        className="w-full"
        disabled={isExporting}
      >
        {isExporting ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Download className="w-4 h-4 mr-2" />
            Export as PDF
          </>
        )}
      </Button>
    </DesktopOnlyFeature>
  );
};
