/**
 * Appendices Section Template
 *
 * Generates appendix sections with metadata, completion stats, and version info.
 */

import type { AggregatedData } from '../formatters/DataAggregator';
import type { ExportMetadata } from '../../MarkdownExportService';
import * as md from '../formatters/MarkdownFormatter';

export function generateAppendices(
  data: AggregatedData,
  metadata: ExportMetadata
): string {
  let content = '';

  // Main section heading
  content += md.heading('Appendices', 2);

  // Appendix A: Completion Status
  content += generateCompletionStatus(data);

  // Appendix B: Export Metadata
  content += generateExportMetadata(metadata);

  content += md.horizontalRule();

  // Footer note
  content += md.paragraph(
    md.italic(
      'This document was generated by IDEA Brand Coach and represents the current state of your brand strategy. ' +
      'This is a living document that evolves with your brand.'
    )
  );

  return content;
}

/**
 * Generate completion status appendix
 */
function generateCompletionStatus(data: AggregatedData): string {
  let content = '';

  content += md.heading('A. Completion Status', 3);

  const stats = data.metadata.completionStats;

  const statusData: string[][] = [
    ['IDEA Insight', `${stats.insight || 0}%`],
    ['IDEA Distinctive', `${stats.distinctive || 0}%`],
    ['IDEA Empathy', `${stats.empathy || 0}%`],
    ['IDEA Authentic', `${stats.authentic || 0}%`],
    ['Customer Avatar', `${stats.avatar || 0}%`],
    ['Brand Canvas', `${stats.canvas || 0}%`],
  ];

  content += md.table(['Section', 'Completion'], statusData);

  return content;
}

/**
 * Generate export metadata appendix
 */
function generateExportMetadata(metadata: ExportMetadata): string {
  let content = '';

  content += md.heading('B. Export Metadata', 3);

  const metadataInfo: Record<string, string> = {
    'Export Schema Version': metadata.exportVersion,
    'Generated': md.formatTimestamp(metadata.generatedAt),
    'User ID': anonymizeUserId(metadata.userId),
  };

  content += md.metadataBlock(metadataInfo);

  content += md.paragraph(md.bold('Data Sources:'));

  const dataSources: string[] = [
    `Knowledge Base entries: ${metadata.dataSources.knowledgeEntries}`,
    `Chat sessions: ${metadata.dataSources.chatSessions}`,
    `Chat messages: ${metadata.dataSources.chatMessages}`,
    `Overall completion: ${metadata.dataSources.completionPercentage}%`,
  ];

  content += md.unorderedList(dataSources);

  return content;
}

/**
 * Anonymize user ID for privacy (keep first 8 chars)
 */
function anonymizeUserId(userId: string): string {
  if (userId.length <= 8) return userId;
  return userId.substring(0, 8) + '...';
}
