/**
 * Diagnostic Results PDF Export Component
 *
 * Generates a PDF export of brand diagnostic results using the markdown-based
 * PDF export strategy.
 */

import React from 'react';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { MarkdownPDFExporter, type PDFExportConfig } from './MarkdownPDFExporter';
import * as md from './templates/formatters/MarkdownFormatter';

/**
 * Diagnostic data structure
 */
interface DiagnosticData {
  answers: Record<string, string>;
  scores: {
    insight: number;
    distinctive: number;
    empathetic: number;
    authentic: number;
  };
  overallScore: number;
  completedAt: string;
}

/**
 * Category details for IDEA framework
 */
const CATEGORY_DETAILS = {
  insight: {
    title: 'Insight Driven',
    description: 'Understanding customer motivations and emotional triggers',
  },
  distinctive: {
    title: 'Distinctive',
    description: 'Standing out with unique brand assets and positioning',
  },
  empathetic: {
    title: 'Empathetic',
    description: 'Connecting emotionally with your audience',
  },
  authentic: {
    title: 'Authentic',
    description: 'Building genuine, transparent brand relationships',
  },
};

/**
 * Diagnostic Results PDF Exporter
 */
class DiagnosticResultsExporter extends MarkdownPDFExporter {
  private diagnosticData: DiagnosticData;
  private companyName: string;

  constructor(
    diagnosticData: DiagnosticData,
    companyName: string = 'Your Brand',
    config: Partial<PDFExportConfig> = {}
  ) {
    super({
      title: 'Brand Diagnostic Results',
      subtitle: companyName,
      primaryColor: [30, 64, 175],
      footerText: 'Generated by IDEA Brand Coach',
      ...config,
    });

    this.diagnosticData = diagnosticData;
    this.companyName = companyName;
  }

  /**
   * Generate markdown content for diagnostic results
   */
  protected generateMarkdown(): string {
    let content = '';

    // Header
    content += md.heading(`${this.companyName} - Brand Diagnostic Results`, 1);
    content += md.blockquote(`Generated by IDEA Brand Coach on ${md.formatDate(new Date())}`);
    content += md.horizontalRule();

    // Executive Summary
    content += this.generateExecutiveSummary();

    // Overall Score
    content += this.generateOverallScore();

    // Category Breakdown
    content += this.generateCategoryBreakdown();

    // Recommendations
    content += this.generateRecommendations();

    // Next Steps
    content += this.generateNextSteps();

    // Footer
    content += this.generateFooter();

    return content;
  }

  /**
   * Generate executive summary section
   */
  private generateExecutiveSummary(): string {
    let content = '';

    content += md.heading('Executive Summary', 2);

    const level = this.getScoreLevel(this.diagnosticData.overallScore);

    content += md.paragraph(
      `This diagnostic assessment evaluates your brand across the four dimensions of the ` +
      `${md.bold('IDEA Strategic Brand Framework™')}: Insight-Driven, Distinctive, Empathetic, and Authentic. ` +
      `Your overall brand health score is ${md.bold(`${this.diagnosticData.overallScore}%`)}, ` +
      `rated as ${md.bold(level.level)}.`
    );

    content += md.metadataBlock({
      'Assessment Date': md.formatDate(this.diagnosticData.completedAt),
      'Overall Score': `${this.diagnosticData.overallScore}%`,
      'Rating': level.level,
    });

    content += md.horizontalRule();

    return content;
  }

  /**
   * Generate overall score section
   */
  private generateOverallScore(): string {
    let content = '';

    content += md.heading('Overall Brand Health Score', 2);

    const level = this.getScoreLevel(this.diagnosticData.overallScore);

    content += md.table(
      ['Metric', 'Value'],
      [
        ['Score', `${this.diagnosticData.overallScore}%`],
        ['Rating', level.level],
        ['Status', level.status],
      ]
    );

    content += md.paragraph(
      `Your brand shows ${level.level.toLowerCase()} performance across the IDEA framework dimensions. ` +
      level.description
    );

    content += md.horizontalRule();

    return content;
  }

  /**
   * Generate category breakdown section
   */
  private generateCategoryBreakdown(): string {
    let content = '';

    content += md.heading('IDEA Framework Category Breakdown', 2);

    // Summary table
    content += md.table(
      ['Category', 'Score', 'Rating'],
      Object.entries(this.diagnosticData.scores).map(([category, score]) => {
        const details = CATEGORY_DETAILS[category as keyof typeof CATEGORY_DETAILS];
        const level = this.getScoreLevel(score);
        return [details.title, `${score}%`, level.level];
      })
    );

    // Detailed breakdown
    Object.entries(this.diagnosticData.scores).forEach(([category, score]) => {
      const details = CATEGORY_DETAILS[category as keyof typeof CATEGORY_DETAILS];
      const level = this.getScoreLevel(score);

      content += md.heading(details.title, 3);
      content += md.paragraph(md.italic(details.description));
      content += md.unorderedList([
        `${md.bold('Score')}: ${score}%`,
        `${md.bold('Rating')}: ${level.level}`,
        `${md.bold('Status')}: ${level.status}`,
      ]);

      // Category-specific insight
      content += md.paragraph(this.getCategoryInsight(category as keyof typeof CATEGORY_DETAILS, score));
    });

    content += md.horizontalRule();

    return content;
  }

  /**
   * Generate recommendations section
   */
  private generateRecommendations(): string {
    let content = '';

    content += md.heading('Key Recommendations', 2);

    // Find weakest area
    const weakestArea = Object.entries(this.diagnosticData.scores).reduce(
      (min, [key, value]) => (value < min.score ? { area: key, score: value } : min),
      { area: '', score: 100 }
    );

    const primaryRecommendation = this.getRecommendation(
      weakestArea.area as keyof typeof CATEGORY_DETAILS
    );

    content += md.heading('Primary Focus Area', 3);
    content += md.paragraph(
      `Your ${md.bold(CATEGORY_DETAILS[weakestArea.area as keyof typeof CATEGORY_DETAILS]?.title || 'brand')} ` +
      `dimension scored ${weakestArea.score}%, which is your area of greatest opportunity.`
    );
    content += md.blockquote(primaryRecommendation);

    // All recommendations
    content += md.heading('All Dimension Recommendations', 3);

    const recommendations = Object.entries(this.diagnosticData.scores)
      .sort(([, a], [, b]) => a - b)
      .map(([category]) => {
        const details = CATEGORY_DETAILS[category as keyof typeof CATEGORY_DETAILS];
        const rec = this.getRecommendation(category as keyof typeof CATEGORY_DETAILS);
        return `${md.bold(details.title)}: ${rec}`;
      });

    content += md.orderedList(recommendations);

    content += md.horizontalRule();

    return content;
  }

  /**
   * Generate next steps section
   */
  private generateNextSteps(): string {
    let content = '';

    content += md.heading('Next Steps', 2);

    content += md.paragraph(
      'Based on your diagnostic results, here are recommended actions to strengthen your brand:'
    );

    const steps = [
      `${md.bold('Create an Account')}: Sign up to save your results and access premium tools`,
      `${md.bold('Start Brand Coaching')}: Get personalized AI coaching based on these results`,
      `${md.bold('Complete Avatar Builder')}: Define your ideal customer profile`,
      `${md.bold('Build Your Brand Canvas')}: Create a comprehensive brand strategy`,
      `${md.bold('Use ValueLens')}: Generate brand-aligned copy and content`,
    ];

    content += md.orderedList(steps);

    content += md.horizontalRule();

    return content;
  }

  /**
   * Generate footer section
   */
  private generateFooter(): string {
    let content = '';

    content += md.heading('About This Assessment', 2);

    content += md.paragraph(
      'This diagnostic is based on the IDEA Strategic Brand Framework™, a proven methodology ' +
      'for building strong, distinctive brands. The framework evaluates brands across four ' +
      'interconnected dimensions that together create lasting brand value.'
    );

    content += md.paragraph(
      `${md.bold('Learn more')}: Visit IDEA Brand Coach to explore tools, resources, and ` +
      'personalized coaching to strengthen your brand.'
    );

    content += md.horizontalRule();

    content += md.paragraph(
      md.italic(`© ${new Date().getFullYear()} IDEA Brand Coach. All rights reserved.`)
    );

    return content;
  }

  /**
   * Get score level information
   */
  private getScoreLevel(score: number): { level: string; status: string; description: string } {
    if (score >= 80) {
      return {
        level: 'Excellent',
        status: 'Strong foundation in place',
        description: 'Continue to build on your strengths while looking for opportunities to innovate.',
      };
    }
    if (score >= 60) {
      return {
        level: 'Good',
        status: 'Solid performance with room for growth',
        description: 'Focus on strengthening specific areas to move from good to great.',
      };
    }
    if (score >= 40) {
      return {
        level: 'Fair',
        status: 'Developing foundation',
        description: 'Prioritize building core brand fundamentals in this area.',
      };
    }
    return {
      level: 'Needs Improvement',
      status: 'Significant opportunity for growth',
      description: 'This area requires focused attention and strategic investment.',
    };
  }

  /**
   * Get category-specific insight
   */
  private getCategoryInsight(category: keyof typeof CATEGORY_DETAILS, score: number): string {
    const insights: Record<keyof typeof CATEGORY_DETAILS, Record<string, string>> = {
      insight: {
        high: 'Your brand demonstrates strong customer understanding and market awareness.',
        medium: 'Consider deepening your customer research to uncover more actionable insights.',
        low: 'Prioritize customer research and market analysis to build a stronger foundation.',
      },
      distinctive: {
        high: 'Your brand stands out clearly in the market with unique positioning.',
        medium: 'Look for opportunities to sharpen your differentiation and unique value.',
        low: 'Focus on identifying what makes your brand truly unique and communicate it clearly.',
      },
      empathetic: {
        high: 'Your brand creates strong emotional connections with customers.',
        medium: 'Explore ways to deepen emotional engagement in your brand communications.',
        low: 'Work on understanding customer emotions and creating more meaningful connections.',
      },
      authentic: {
        high: 'Your brand is perceived as genuine and trustworthy.',
        medium: 'Look for opportunities to strengthen brand authenticity and transparency.',
        low: 'Focus on building trust through consistent, genuine brand behavior.',
      },
    };

    const level = score >= 70 ? 'high' : score >= 50 ? 'medium' : 'low';
    return insights[category][level];
  }

  /**
   * Get recommendation for category
   */
  private getRecommendation(category: keyof typeof CATEGORY_DETAILS): string {
    const recommendations: Record<keyof typeof CATEGORY_DETAILS, string> = {
      insight:
        'Focus on customer research and behavioral analysis to understand what truly motivates your audience. Consider conducting interviews, surveys, and analyzing customer data.',
      distinctive:
        'Develop unique brand assets and positioning that clearly differentiate you from competitors. Identify your unique value proposition and communicate it consistently.',
      empathetic:
        'Create deeper emotional connections through storytelling and authentic customer experiences. Focus on understanding and addressing customer pain points and aspirations.',
      authentic:
        'Build transparency and trust through genuine brand communication and consistent values. Ensure your brand promise matches your actual customer experience.',
    };

    return recommendations[category];
  }

  /**
   * Get suggested filename for download
   */
  protected getFilename(): string {
    const slug = this.companyName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');

    const date = new Date().toISOString().split('T')[0];
    return `${slug}-diagnostic-results-${date}.pdf`;
  }
}

/**
 * Props for DiagnosticResultsPDFExport component
 */
interface DiagnosticResultsPDFExportProps {
  diagnosticData: DiagnosticData;
  companyName?: string;
  variant?: 'default' | 'outline' | 'ghost';
  className?: string;
}

/**
 * Diagnostic Results PDF Export Component
 */
export function DiagnosticResultsPDFExport({
  diagnosticData,
  companyName = 'Your Brand',
  variant = 'outline',
  className = '',
}: DiagnosticResultsPDFExportProps): JSX.Element {
  const { toast } = useToast();

  const handleExport = async (): Promise<void> => {
    try {
      const exporter = new DiagnosticResultsExporter(diagnosticData, companyName);
      await exporter.export();

      toast({
        title: 'PDF Generated Successfully',
        description: 'Your diagnostic results have been downloaded.',
      });
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: 'Export Error',
        description: 'There was an error generating the PDF. Please try again.',
        variant: 'destructive',
      });
    }
  };

  return (
    <Button onClick={handleExport} variant={variant} className={className}>
      <Download className="w-4 h-4 mr-2" />
      Download PDF Report
    </Button>
  );
}

/**
 * Export the exporter class for programmatic use
 */
export { DiagnosticResultsExporter };
