// This file is automatically generated. Do not edit it directly.
// EXCEPTION: the Clerk-native-auth branch below is a hand-maintained, flag-gated
// addition (see docs/integrations/CLERK_SETUP.md). If you regenerate this file,
// re-apply the `isClerkAuthEnabled()` branch.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isClerkAuthEnabled } from '../../config/clerkConfig';
import { getSupabaseAccessToken } from './sessionToken';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ecdrxtbclxfpkknasmrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZHJ4dGJjbHhmcGtrbmFzbXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODE5ODYsImV4cCI6MjA2OTU1Nzk4Nn0.yPlOSq4l4PMD9RlchTBeXs5EBmzggGQGp7A8B3qGAAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Clerk native third-party auth (flag-gated): in Clerk mode the client sends the
// live Clerk session token as the bearer on every request via `accessToken`,
// rather than persisting its own Supabase-Auth session. RLS then resolves the
// caller as `auth.jwt()->>'sub'` (the Clerk user id). With the flag OFF this is
// byte-for-byte the original generated client.
export const supabase = isClerkAuthEnabled()
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      accessToken: () => getSupabaseAccessToken(),
    })
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });