/**
 * DraftCountermeasureDialog (Competitor-Agents P4 — the lift loop)
 *
 * Opened from TouchpointCompetitorAgentPanel's "Draft countermeasure" CTA. It
 * closes the lift loop in three steps:
 *  1. Draft — routes the competitor insight's `gap_to_our_avatar` +
 *     `strategic_angle` (the competitor brief) into the `funnel-rewrite` edge fn
 *     and shows the on-brand rewrite.
 *  2. Compose — the rewrite becomes Variant B against the current copy
 *     (Variant A) via the shared test-design composer (the existing designTest
 *     path), recorded into `brand_tests`.
 *  3. Record — the test is tagged `competitor_insight_applied = true` so the
 *     Testing & Lift tab can surface competitor-informed tests (ST-4 / LT-5).
 *
 * GROUNDING GATE: the rewrite is generated by the edge fn from the supplied
 * brief + brand context; competitor names are passed as context only and never
 * appear in the copy (the fn's prompt forbids it). The user can edit the rewrite
 * before recording, so nothing is fabricated on their behalf.
 *
 * Plan: docs/brand-funnel-builder/COMPETITOR_AGENTS_PLAN.md (ST-4)
 */

import React, { useState } from 'react';
import { Loader2, Sparkles, FlaskConical } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useCompetitorInsights } from '@/hooks/useCompetitorInsights';
import type { CompetitorBrief } from '@/types/competitorInsights';

interface DraftCountermeasureDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** The asset (funnel piece) the countermeasure targets. */
  assetId: string;
  /** The touchpoint this asset belongs to. */
  touchpointId: string;
  touchpointLabel: string;
  /** Avatar the test is scoped to (required to record into brand_tests). */
  avatarId?: string;
  /** The competitor brief that drives the rewrite + flags the test. */
  competitorBrief: CompetitorBrief;
  /** The persisted insight this countermeasure is informed by, if any. */
  competitiveInsightId?: string | null;
  /** The asset's current copy (Variant A / baseline). */
  currentCopy?: string;
  /** Optional context passed through to the rewrite. */
  avatarContext?: unknown;
  positioningStatementContext?: unknown;
  /** Channel hint for the test's default primary metric. */
  channel?: string;
}

export function DraftCountermeasureDialog({
  open,
  onOpenChange,
  assetId,
  touchpointId,
  touchpointLabel,
  avatarId,
  competitorBrief,
  competitiveInsightId,
  currentCopy,
  avatarContext,
  positioningStatementContext,
  channel,
}: DraftCountermeasureDialogProps): React.ReactElement {
  const { draftCountermeasure, recordTest, isDrafting, isRecordingTest } = useCompetitorInsights();

  const [rewrite, setRewrite] = useState<string>('');
  const [angleNote, setAngleNote] = useState<string>('');
  const [baseline, setBaseline] = useState<string>(currentCopy ?? '');
  const [testName, setTestName] = useState<string>(`Countermeasure: ${touchpointLabel}`);
  const [recorded, setRecorded] = useState<boolean>(false);

  const handleDraft = async (): Promise<void> => {
    const result = await draftCountermeasure({
      touchpointId,
      currentCopy,
      competitorBrief,
      avatarContext,
      positioningStatementContext,
    });
    if (result) {
      setRewrite(result.rewrite);
      setAngleNote(result.angleNote);
    }
  };

  const handleRecord = async (): Promise<void> => {
    if (!avatarId) return;
    const test = await recordTest({
      avatarId,
      assetId,
      competitiveInsightId: competitiveInsightId ?? null,
      touchpointId,
      name: testName.trim() || `Countermeasure: ${touchpointLabel}`,
      baselineCopy: baseline,
      rewriteCopy: rewrite,
      channel,
      // Competitor-informed by construction (this is the countermeasure path).
      competitorInsightApplied: true,
    });
    if (test) setRecorded(true);
  };

  const canRecord = Boolean(avatarId) && rewrite.trim() !== '' && baseline.trim() !== '';

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Draft a countermeasure</DialogTitle>
          <DialogDescription>
            Turn the strategic angle into an on-brand rewrite, then run it as an A/B test against your
            current {touchpointLabel} copy.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* The competitor brief driving the rewrite. */}
          {competitorBrief.strategic_angle && (
            <div className="rounded-md border border-primary/30 bg-primary/5 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Strategic angle
              </p>
              <p className="mt-1 text-sm">{competitorBrief.strategic_angle}</p>
            </div>
          )}

          {/* Step 1 — draft the rewrite */}
          <Button onClick={() => void handleDraft()} disabled={isDrafting} variant="secondary">
            {isDrafting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Drafting rewrite...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                {rewrite ? 'Re-draft rewrite' : 'Draft rewrite'}
              </>
            )}
          </Button>

          {/* The drafted rewrite (Variant B) — editable before recording. */}
          {rewrite && (
            <div className="space-y-2">
              {angleNote && <p className="text-xs text-muted-foreground">{angleNote}</p>}
              <Label htmlFor="cm-rewrite">Variant B — competitor-informed rewrite</Label>
              <Textarea
                id="cm-rewrite"
                value={rewrite}
                onChange={(e) => setRewrite(e.target.value)}
                rows={5}
              />
            </div>
          )}

          {/* Variant A — baseline (editable; prefilled from current copy) */}
          <div className="space-y-2">
            <Label htmlFor="cm-baseline">Variant A — current copy (baseline)</Label>
            <Textarea
              id="cm-baseline"
              value={baseline}
              onChange={(e) => setBaseline(e.target.value)}
              rows={3}
              placeholder="Paste the current copy for this touchpoint to test against."
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="cm-name">Test name</Label>
            <Input id="cm-name" value={testName} onChange={(e) => setTestName(e.target.value)} />
          </div>

          {!avatarId && (
            <p className="text-xs text-muted-foreground">
              Recording a test requires an avatar. Open the funnel for a specific brand to record lift
              tests.
            </p>
          )}
          {recorded && (
            <p className="text-xs text-primary">
              Recorded as a competitor-informed A/B test. See the Tests tab for lift tracking.
            </p>
          )}
        </div>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={() => void handleRecord()} disabled={!canRecord || isRecordingTest}>
            {isRecordingTest ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Recording test...
              </>
            ) : (
              <>
                <FlaskConical className="mr-2 h-4 w-4" />
                Compose &amp; record A/B test
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
