#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Interactive Onboarding Tour

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting main service (React Frontend)${NC}"
echo ""

# Navigate to project root and start development server
cd /Users/matthewkerns/workspace/idea-brand-coach

# Install react-joyride dependency if not already installed
if ! grep -q "react-joyride" package.json; then
    echo "Installing react-joyride dependency..."
    bun add react-joyride
fi

# Start Vite dev server in background
npm run dev &
DEV_SERVER_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend (main)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend (main): http://localhost:3000"
echo ""
echo "Development server PID: $DEV_SERVER_PID"
echo ""
echo "To stop services, run:"
echo "  kill $DEV_SERVER_PID"
echo ""
echo "========================================"
echo "Ready to implement Interactive Onboarding Tour"
echo "========================================"
echo ""
